### ISSUE TITLE
Problem when used with Minify HTML extension

### ISSUE THREAD

**Issue by saltpeanuts** [cdowdy/boltbetterthumbs#18]
When used alongside the Minify HTML extension: https://github.com/nlemoine/bolt-extension-minify-html 

Srcset images are not loaded. Looking at the network monitor I'm seeing a 500 error for each image.

Images are still being generated and cached.

The original passthrough image is loading fine.

Did a very quick comparison of the minified vs original srcset markup to see if it's getting mangled somewhere by the minifier, but nothing immediately jumps out as being obviously out of place. Only had time for a very brief look, though.

**Comment by cdowdy** [comment]
@saltpeanuts this isn't an error for this extension. 

if you open the image in a separate tab you'll get:

`LogicException in StreamedResponse.php line 124: 
The content cannot be set on a StreamedResponse instance.`  

and I modified it to actually run in debug mode and you'll get:  

![minify-error](https://cloud.githubusercontent.com/assets/5969974/21939642/b97cb6a4-d98e-11e6-8403-47b4643f9a7f.png)


This uses Symfony StreamedResponse and sets a notModified header so you'll need to open a bug over at the minify repo

can show them these if you'd like:

https://github.com/symfony/symfony/issues/15564  

https://github.com/symfony/symfony/issues/17036

**Comment by saltpeanuts** [comment]
@cdowdy oh, totally. I knew it wasn't a boltbetterthumbs bug exactly, just an issue when they're both used together so thought you'd still want a heads up. They're both common tasks so not unusual for people to run them at the same time. I'll let @nlemoine know too.

**Comment by cdowdy** [comment]
oh alright.. haha I saw the bug report and thought I messed up something... Thanks for the heads up!

**Comment by cdowdy** [comment]
hey @saltpeanuts I decided to tinker a bit and have something that might work you wanna take a look?

**Comment by cdowdy** [comment]
@saltpeanuts err.... nevermind I actually just went to the minify repo and saw they put a check in for a streamed response... nevermind haha.. Thanks though!
