### ISSUE TITLE
Attempting to make image results in an intervention exception

### ISSUE THREAD

**Issue by Maelstromeous** [cdowdy/boltbetterthumbs#3]
![dev sm img projects 0 lual cover jpeg w 1000 s 0a161d3762b889e6a6829e851bd9827b](https://cloud.githubusercontent.com/assets/1776058/20629864/91d0ec04-b325-11e6-8fcb-4bdcb6ab9a5c.png)

**Comment by cdowdy** [comment]
I think I got this fixed! (fingers crossed haha) Thanks for the testing @Maelstromeous !
