### ISSUE TITLE
Twig_Error_Runtime when the image path is empty

### ISSUE THREAD

**Issue by zomars** [cdowdy/boltbetterthumbs#38]
I'm getting the following error when using the `img` tag and the value is empty. 

![captura de pantalla 2017-04-27 a la s 09 16 19](https://cloud.githubusercontent.com/assets/3504472/25490563/76c9cea8-2b2a-11e7-806a-b121431f3119.png)

On my line 17 there's this:
```
{{ img(record.image, 'betterthumbs') }}
```

I don't know if this is the intented behaviour. But seems reasonable to me to check the existence of an image and display a 404 placeholder or don't display anything at all.

Meanwhile I'm using this to check before hand:
```
{% if record.image %}
    {{ img(record.image, 'betterthumbs') }}
{% endif %}
```

**Comment by cdowdy** [comment]
@zomars hmm ok let me spin up a VM this shouldn't happen since there are multiple checks to display a 404 image if the image cannot be found or bolt's 404 image

Thanks!

**Comment by cdowdy** [comment]
@zomars ok I pushed a quick hackfix :) sorry about that I don't know how I skipped over that :(

**Comment by cdowdy** [comment]
Here is how is should look now with all the default settings.  

First image is using ``  {{ img(record.image, 'betterthumbs') }}`` followed by ``  {{ bthumb(record.image, 'single') }}`` then ``{{ srcset(record.image, 'betterthumbs') }}`` and finally ``{{ btsrc(record.image, 'betterthumbs') }}``  

![bolt-extensions dev- laptop with hidpi screen](https://cloud.githubusercontent.com/assets/5969974/25499792/a12935dc-2b5a-11e7-88a8-5e97618c769d.png)

**Comment by zomars** [comment]
Seems good to me. Thanks for the quick response! :)

**Comment by zomars** [comment]
Actually I'm getting the same error but now with images in template fields 😅

**Comment by cdowdy** [comment]
@zomars these fields? https://docs.bolt.cm/3.2/templating/building-templates#template-specific-fields ? 

I'll look at it tomorrow (Wednesday the 3rd) see what else I messed up in the process lol

**Comment by zomars** [comment]
basically if the `img` function receives and empty string as first parameter, that's when Twig starts complaining

**Comment by cdowdy** [comment]
ok @zomars ... I've pushed another attempt to fix this haha.. Hopefully this nips this one. I skipped over template fields like I did for empty record.image... my fault haha.. Sorry about all that ... now go forth and find some more bugs I appreciate it very much!

**Comment by cdowdy** [comment]
I think this is "fixed" so I'm gonna close this for now. if it's not @zomars please do reopen it! Thanks for reporting it to me !
