### ISSUE TITLE
Backend Prime not working when URL uses trailing query string (?locale=en)

### ISSUE THREAD

**Issue by DamienChauvet** [cdowdy/boltbetterthumbs#52]
For instance, the extension Translate adds "?_locale=en" at the end of any BackEnd request.
then the URL for Do Prime is https://my-site.com/bolt?_locale=en/extensions/betterthumbs/files/prime/do, and it does not work properly.

**Comment by cdowdy** [comment]
hey @DamienChauvet thanks! this is definitely a bug with the way I generated the routes! a fix is incoming! Thanks a ton for finding this I don't use  translate so I wouldn't have came across it!
